# Generated by Django 5.1 on 2024-08-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_uploadimage_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Feedback',
        ),
    ]
