# Generated by Django 5.1 on 2024-08-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_note_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImage',
            new_name='Complain',
        ),
    ]
